version: '3'

volumes:
  postgres_local_volume:

services:
  bot-db:
    image: postgres:14.0
    env_file:
      - .env.local
    volumes:
      - postgres_local_volume:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}